
CREATE TABLE Towns
(Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(20) NOT NULL
)
CREATE TABLE Adresses(
Id INT PRIMARY KEY IDENTITY,
AddressText NVARCHAR(MAX)NOT NULL,
TownId INT NOT NULL
CONSTRAINT FK_Addresses_Towns FOREIGN KEY(TownId) REFERENCES Towns(Id)
)
CREATE TABLE Departments(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(20)NOT NULL
)
CREATE TABLE Employees(
Id INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(20) NOT NULL,
MiddleName NVARCHAR(20)NOT NULL,
LastName NVARCHAR(20)NOT NULL,
JobTitle NVARCHAR(20)NOT NULL,
DepartmentId INT NOT NULL
CONSTRAINT FK_Employees_Departments FOREIGN KEY(DepartmentId)REFERENCES Departments(Id),
HireDate DATE NOT NULL,
Salary DECIMAL NOT NULL,
AddressId INT NOT NULL
CONSTRAINT FK_Employees_Adresses FOREIGN KEY (AddressId) REFERENCES Adresses(Id)
)